

#Employers Key Replac
emp_key_adjustments = {
	'J.Crew Group':'J. Crew Group',
	'ICF':'ICF International',
	'Rose':'Rose International',
	'XO':'XO Group Inc',
	'RGA':'Reinsurance Group of America',
	'Hill':'Hill International',
	'Healthcare':'Healthcare Services Group, Inc.',
	'Quad / Graphics':'Quad/Graphics',
	"Frank'S":"Frank's International",
	'Jacobs Engineering Group':'Jacobs Engineering',
	'The Chemours Company':'Chemours',
	'Wells Fargo & Company':'Wells Fargo',
	'ERA':'Era Group',
	'CA':'CA Technologies',
	'Marcus':'Marcus Corporation',
	'Waddell and Reed':'Waddell & Reed Financial',
	'HCA':'HCA Healthcare',
	'CBRE Group':'Cbre',
	'First Merchants':'First Merchants Corporation',
	'Lululemon Athletica':'lululemon athletica',
	'Hershey Company':'Hershey',
	'Hca Healthcare':'HCA Healthcare',
	'Air Products & Chemicals':'Air Products',
	'Deere':'John Deere',
	'Automatic Data Processing':'ADP',
	'Automatic Data Process':'ADP',
	'International Business Machines':'IBM',
	'American Axle & Mfg':'American Axle & Manufacturing',
	'HUB':'Hub Group',
	'American Eagle Outfitter':'American Eagle Outfitters',
	'EY':'Ernst & Young',
	'EY-Parthenon':'Ernst & Young',
	'Kohls':"Kohl's",
	'Hilton Corporate':'Hilton',
	'Chase':'Chase Corp',
	'Procter and Gamble':'Procter & Gamble',
	'Goldman Sachs Asset Management':'Goldman Sachs',
	'Goldman Sachs & Co':'Goldman Sachs',
	'McCormick':'Mccormick & Company',
	'Walt Disney Company':'Walt Disney',
	'Disney':'Walt Disney',
	'Hawaiian':'Hawaiian Airlines',
	'Lowes':"Lowe's",
	'T-Mobile Us':'T-Mobile',
	'BlackBerry Limited':'BlackBerry',
	'Hilti North America':'Hilti',
	'Deloitte Corporate Finance':'Deloitte',
	'Deloitte Consulting':'Deloitte',
	'Citigroup':'Citibank',
	'World Fuel':'World Fuel Services',
	'Biomarin Pharmaceutical':'BioMarin Pharmaceutical',
	'American Airlines Group':'American Airlines',
	'United Technologies Corp. Headquarters':'United Technologies',
	'Bankunited':'BankUnited',
	'Liberty Mutual Insurance Group':'Liberty Mutual',
	'8X8 Inc':'8x8, Inc.',
	'Pnc Financial':'PNC Financial',
	'Citizens':'Citizens Bank',
	'Keyw':'KeyW',
	'Unitedhealth':'UnitedHealth Group',
	'Herc':'Herc Rentals',
	'Harley Davidson':'Harley-Davidson',
	'Imax':'IMAX',
	'MYR':'MYR Group',
	'Bottomline Technologies Inc':'Bottomline Technologies',
	'Alder BioPharmaceuticals Inc.':'Alder BioPharmaceuticals',
	'The RMR Group':'RMR',




}


emp_key_blacklist = {
	'HCI':None,
	'M/I Homes':None,
	'Invitation Homes':None,
	'TRI Pointe Group':None,
	'Barnes':None,
	'Merchants Bank':None,
	'Cooper Companies':None,
	'Crown':None,
	'Cooper':None,
	'Southern':None,
	'PVH':None,
	'American':None,
	'Carlisle':None,
	'Crane':None,
	'Alliance':None,
	'Tower':None,
	'Northwestern':None,
	'Orion':None,
	'Idera Pharmaceuticals':None,
	'Inovio Pharmaceuticals':None,
	'Calyxt':None,
	'Corvus Pharmaceuticals':None,
	'Amicus Therapeutics':None,
	'Versum Materials':None,


	

}



leadiro_changes = {
	'Electronic Arts Inc. (Ea)':'Electronic Arts',
	'Visa Inc. (Visa)':'Visa',
	'Davita Inc.':'Davita',
	'Cross Country Healthcare, Inc. (Cross Country)':'Cross Country Healthcare',
	'Axon Enterprise, Inc. (AXON)':'Axon Enterprise',
	'Owens-Illinois, Inc. (Oi)':'Owens-Illinois',
	'Rbc Capital Markets, LLC (Royal Bank of Canada)':'RBC Capital Markets',
	'Jacobs Engineering Group Inc. (Jacobs)':'Jacobs Engineering',
	'Allergan, Inc. (Allergan)':'Allergan',
	'Mondelez International, Inc. (Mondelez International)':'Mondelez',
	'Zscaler, Inc.':'Zscaler',
	'Dell Inc. (Dell Computer)':'Dell',
	'Vmware, Inc. (DELL EMC)':'Vmware',
	'Caci International Inc.':'CACI',
	'Cotiviti, Inc. (Verscend Technologies, Inc.)':'Cotiviti',
	'Forterra, Inc. (Forterra Building Products)':'Forterra',
	'Allscripts Healthcare Solutions, Inc. (Allscripts)':'Allscripts Healthcare Solutions',
	'Slalom, LLC (Two Degrees)':'Slalom',
	'Owens Corning (Owens Corning)':'Owens Corning',
	'Lamb Weston Inc (Lamb Weston)':'Lamb Weston',
	'Nic Inc. (Nic)':'NIC',
	'Omnicell, Inc. (OMNICELL)':'Omnicell',
	'Waddell & Reed, Inc.':'Waddell & Reed Financial',
	'HCA Inc. (Hospital Coporation of America)':'HCA Healthcare',
	'Adtran, Inc. (Adtran)':'Adtran',
	'Valvoline Inc. (VALVOLINE)':'Valvoline',
	'Ericsson Inc. (Ericsson GE MBL Communications)':'Ericsson',
	'Hd Supply, Inc. (Hd Supply Global Support Ctr)':'HD Supply',
	'Snap Inc. (Snapchat)':'Snap',
	'Basic Energy Services, Inc. (Basic)':'Basic Energy Services',
	'Total System Services, Inc. (TSYS)':'Total System Services',
	'Dataminr, Inc. (Ebh Enterprises, Inc.)':'Dataminr',
	'Icims, Inc. (Icims.com)':'iCIMS',
	'Dropbox, Inc.':'Dropbox',
	'Servicenow, Inc. (SERVICENOW)':'ServiceNow',
	'Smartronix, Inc.':'Smartronix',
	'Ormat Technologies, Inc. (Ormat)':'Ormat Technologies',
	'Compass Minerals International, Inc. (Compass Minerals)':'Compass Minerals',
	'Atn International':'ATN',
	'Atn International, Inc.':'ATN',
	'Rayonier Inc.':'Rayonier',
	'United Services Automobile Association (USAA)':'USAA',
	'Stripe, Inc. (Stripe Payments Company)':'Stripe',
	'Western Alliance Bank (Alliance Bank of Arizona)':'Western Alliance Bank',
	'Jeld-Wen, Inc. (Jeld Wen International Supply)':'Jeld-Wen',
	'Tenable, Inc. (Tenable Network Security)':'Tenable',
	'Matson, Inc. (Matson Construction)':'Matson',
	'Tempur Sealy International, Inc. (TEMPUR SEALY INTERNATIONAL)':'Tempur Sealy',
	'Titan International, Inc.':'Titan',
	'Retrophin, Inc.':'Retrophin',
	'Aqua America, Inc. (AQUA)':'Aqua America',
	'Wesco Inc. (On Your Way)':'Wesco',
	'Cubesmart (Cubessmart Self Stor Logistics)':'Cubesmart',
	'Nine Energy Service, Inc. (Nine)':'Nine Energy Service',
	'Caleres, Inc. (FAMOUS FOOTWEAR)':'Caleres',
	'Garmin International, Inc.':'Garmin',
	'Syntel, Inc. (Atos Syntel)':'Syntel',
	'Haynes International, Inc.':'Haynes International',
	'Fanatics, Inc. (Football Fanatics)':'Fanatics',
	'Verastem, Inc. (Verastem Oncology)':'Verastem',
	'Guess , Inc. (GUESS?)':'Guess',
	'Amazon Web Services, Inc.':'Amazon',
	'Zillow, Inc. (Zillow.com)':'Zillow',
	'Air Products and Chemicals, Inc. (Air Products)':'Air Products',
	'Mettler-Toledo International Inc.':'Mettler Toledo',
	'Plante & Moran, Pllc':'Plante Moran',
	'Healthcare Services Group Inc (Healthcare)':'Healthcare Services Group, Inc.',
	'Johnson Outdoors Inc.':'Johnson Outdoors',
	'E. I. Du Pont De Nemours and Company (Dupont)':'DuPont',
	'Weyerhaeuo':'Weyerhaeuser',
	'Jabil Circuit, Inc. (JABIL CIRCUIT, INC.)':'Jabil',
	'Astronics Advanced Electronic Systems Corp. (Astronics-Aes)':'Astronics',
	'CBS Corporation':'CBS',
	'The Hartford Financial Services Group Inc (Hartford, The)':'The Hartford',
	'The Progressive Corporation (PROGRESSIVE INSURANCE)':'Progressive',
	'Celanese Americas LLC (Kep Americas)':'Celanese',
	'Amphenol Corporation (Amphenol Rf)':'Amphenol',
	'Automatic Data Processing, Inc. (ADP)':'ADP',
	'International Business Machines Corporation (IBM)':'IBM',
	'LG&e and Ku Energy LLC (PPL)':'PPL',
	'Vf Jeanswear Limited Partnership (Vf)':'VF',
	'Ball Aerospace & Technologies Corporation (Ball)':'Ball',
	'Heinz Kraft Foods Company':'Kraft Heinz',
	'Agile Enterprise Solutions, Inc. (AES)':'AES',
	'Archer-Daniels-Midland Company (ADM)':'Archer Daniels Midland',
	'Becton, Dickinson and Company (B D)':'Becton Dickinson & Company',
	'Harmonic Inc. (HARMONIC)':'Harmonic',
	'Hollyfrontier Corporation (Hollyfrontier)':'HollyFrontier',
	'Williams-Sonoma, Inc. (WILLIAMS SONOMA)':'Williams-Sonoma',
	'Harmonic Inc. (HARMONIC)':'Harmonic',
	'Conocophillips Company':'ConocoPhillips',
	'American Axle & Manufacturing, Inc. (AAMCO Transmissions)':'American Axle & Manufacturing',
	'Audioeye, Inc.':'AudioEye',
	'American Electric Power Company, Inc. (AEP)':'American Electric Power',
	'Costco Wholesale Corporation':'Costco',
	'Quanta Services, Inc. (QUANTA SERVICES)':'Quanta Services',
	'Leaf Group Ltd. (Demand Media)':'Leaf Group',
	'American Eagle Outfitters, Inc. (AMERICAN EAGLE OUTFITTERS)':'American Eagle Outfitters',
	'Sonic Automotive, Inc. (Sonic Automotive)':'Sonic Automotive',
	'Welltower Inc. (Welltower)':'Welltower',
	'Norfolk Southern Corporation':'Norfolk Southern',
	'The Valspar Corporation (Sherwin-Williams)':'Sherwin-Williams',
	"Kohl's Department Stores, Inc. (Kohl's)":"Kohl's",
	'Tri Pointe Group, Inc. (TRI POINTE GROUP)':'Tri Pointe',
	"The Procter & Gamble Company (P&G)":'Procter & Gamble',
	'First Merchants Bank':'First Merchants Corporation',
	'Jpmorgan Chase & Co.':'JP Morgan Chase',
	'Snowflake Computing, Inc.':'Snowflake',
	'American International Group, Inc. (AIG)':'AIG',
	'Berkshire Hathaway Homestate Insurance Company (Berkshire Hathaway)':'Berkshire Hathaway',
	'Black Knight Financial Services, Inc. (Black Knight)':'Black Knight',
	'PWC STRategy& (us) LLC':'PWC',
	'Qiagen North American Holdings Inc.':'Qiagen',
	'Cisco Systems, Inc. (Cisco Systems)':'Cisco',
	'Keller Williams Realty, Inc. (Keller Williams Realtors)':'Keller Williams',
	'Robert W. Baird & Co. Incorporated':'Baird',
	'Donaldson Company, Inc. (Donaldson Filtration Solutions)':'Donaldson',
	'Two Sigma Investments, LP (Two Sigma Investor Solutions)':'Two Sigma',
	'Sap America, Inc.':'SAP',
	'T-Mobile Us, Inc.':'T-Mobile',
	'Veeam Software Corporation':'Veeam',
	'Snap-On Incorporated (Snap-On Tools)':'Snap-On',
	'Onemain Holdings, Inc. (SPRINGLEAF)':'Onemain',
	'Citadel Enterprise Americas LLC':'Citadel',
	'Blackberry Corp. (Blackberry)':'BlackBerry',
	'Slack Technologies, Inc.':'Slack',
	'Parexel International Corporation':'Parexel',
	'UBS Financial Services Inc. (UBS Global Asset MGT Americas)':'UBS',
	'Zs Associates, Inc. (Zs Associates)':'ZS',
	'Memorial Sloan-Kettering Cancer Center':'Memorial Sloan Kettering',
	'Asset Balyasny Management L P':'Balyasny Asset Management',
	'Deloitte LLP':'Deloitte',
	'ITT Inc. (ITT)':'ITT',
	'Arconic Inc.':'Arconic',
	'Portland General Electric Company (Portland General Electric)':'Portland General Electric',
	'Maxlinear, Inc.':'MaxLinear',
	'The New York Times Company':'New York Times',
	'Citigroup Inc. (Citibank)':'Citibank',
	'Tops Markets, LLC (Tops Friendly Markets)':'Tops',
	'Wyndham Hotel Group, LLC (Knights Inn)':'Wyndham Hotels & Resorts',
	'Tivo Solutions Inc.':'Tivo',
	'World Fuel Services Corp (World Fuel)':'World Fuel Services',
	'Nokia Solutions and Networks US LLC (Nokia)':'Nokia',
	'Fossil Partners, L.P. (Sketchers)':'Fossil',
	'Cabot Microelectronics Corporation':'Cabot Microelectronics',
	'Aspen Insurance U.S. Services, Inc. (Aspen Specialty)':'Aspen Insurance',
	'Keurig Dr Pepper Inc. (Dr Pepper Snapple)':'Dr Pepper Snapple Group',
	'Westwood Financial Corp.':'Westwood',
	'Hilltop Holdings Inc. (Hilltop Holdings)':'Hilltop',
	'American Airlines, Inc.':'American Airlines',
	'United Technologies Corporation (UTC)':'United Technologies',
	'Bankunited, Inc. (BANKUNITED)':'BankUnited',
	'Amyris, Inc. (Amyris)':'Amyris',
	'CTS International, Inc.':'CTS',
	'Graftech International Ltd. (GRAFTECH INTERNATIONAL)':'Graftech',
	'Iqvia Inc. (Quintilesims)':'Iqvia',
	'Algolia, Inc. (Seaurchin. Io.)':'Algolia',
	'8x8, Inc. (8x8)':'8x8, Inc.',
	'Noble Holding (u.s.) Corporation (Noble)':'Noble',
	'The ADT Security Corporation (ADT Security Services)':'ADT',
	'Universal City Development Partners, Ltd. (Universal Orlando)':'Universal',
	'Timkensteel Corporation (Timkensteel)':'Timkensteel',
	'Alamo Group Inc. (Alamo Group)':'Alamo',
	'Trustmark Mutual Holding Company (Trustmark Companies)':'Trustmark',
	'The PNC Financial Services Group Inc (PNC)':'PNC Financial',
	'Cengage Learning, Inc. (Course Technology)':'Cengage',
	'Revlon Consumer Products Corporation':'Revlon',
	'West Pharmaceutical Services, Inc. (WEST)':'West Pharmaceutical',
	'The RMR Group LLC':'RMR',
	'Aptiv Corporation (Delphi)':'Aptiv',
	'Atkore International Group Inc.':'Atkore',
	'The Keyw Corporation':'KeyW',
	'UGI Corporation':'UGI',
	'Eqt Corporation':'EQT',
	'Bpm San Francisco (B P M)':'BPM',
	"Bojangles' Restaurants, Inc. (Bojangle's)":"Bojangles'",
	'Nomura Holding America Inc.':'Nomura',
	'Unitedhealth Group Incorporated (Unitedhealth Group)':'UnitedHealth Group',
	'Herc Rentals Inc.':'Herc Rentals',
	'Genpact Process Solutions LLC':'Genpact',
	'Primoris Services Corporation':'Primoris',
	'The Vail Corporation (Vail Resorts Management Co)':'Vail Resorts',
	'National Planning Corporation (Guardian Life)':'Guardian Life Insurance Company',
	'R. R. Donnelley & Sons Company (RR Donnelley)':'R.R. Donnelley & Sons',
	'Harley-Davidson Motor Company, Inc. (Harley-Davidson)':'Harley-Davidson',
	'The TJX Companies Inc (T.J. Maxx)':'TJX',
	'Imax Corporation (Imax Worldwide Imports)':'IMAX',
	'Flextronics International Usa, Inc. (Flex)':'Flex',
	'Parker-Hannifin Corporation':'Parker Hannifin',
	'Myr Group Inc. (Myr Group)':'MYR Group',
	'Great American Insurance Company (Great American)':'Great American Insurance Group',
	'Baker & McKenzie LLP':'Baker McKenzie',
	'Zayo Group Holdings, Inc.':'Zayo',
	'Coca-Cola Refreshments Usa, Inc. (Coca-Cola)':'Coca-Cola',
	'Discovery, Inc. (DISCOVERY COMMUNICATIONS)':'Discovery',
	'Cantel Medical Corp. (Cantel)':'Cantel Medical Corporation',
	'Bottomline Technologies (de), Inc.':'Bottomline Technologies',
	'Alder Biopharmaceuticals, Inc.':'Alder BioPharmaceuticals',



}


blacklist_companies = {
	'Speedway LLC':None,
	'Williams International Co LLC (Willc)':None,
	'Crane & Co., Inc. (Crane Currency)':None,
	'Spectrum, Inc. (Spectrum Laboratories)':None,
	'Chase International Inc (Chase Intl Dstinctive Property)':None,
	'Roberts Markel Weinberg Butler Hailey PC':None,
	'Gap Solutions, Inc.':None,
	'Loews Hotels Holding Corporation (Loews Hotels & Resorts)':None,
	'Deere Hitachi':None,
	'Asbury Automotive Group (Spectrum Sound)':None,
	'Cellular Plus (T-Mobile Authorized Retailer)':None,
	'Citizens, Inc.':None,
	'Idera Pharmaceuticals, Inc. (Idera)':None,
	'Inovio Pharmaceuticals, Inc. (Inovio)':None,
	'Calyxt, Inc.':None,
	'Corvus Pharmaceuticals, Inc. (Corvus Pharmaceuticals)':None,
	'Amicus Therapeutics, Inc.':None,
	'Versum Materials, Inc.':None,
	'Booking Holdings Inc.':None,
	'Frontline Source Group, Inc.':None,
	'Coca-Cola Bottling Company United, Inc. (Coca-Cola)':None,
}


