company_replacements = {
		'Exxon Mobil':'ExxonMobil',
		'Berkshire Hathaway':'Geico',
		'Amazon.com':'Amazon',
		'Amazon Com':'Amazon',
		'Walgreens Boots Alliance':'Walgreens',
		'Zions Bancorp':'Zions Bancorporation',
		'J.P. Morgan':'JP Morgan Chase',
		'J.P. Morgan Chase':'JP Morgan Chase',
		'Jpmorgan Chase & Company':'JP Morgan Chase',
		'J.P. Morgan Asset Management':'JP Morgan Chase',
		'salesforce.com':'Salesforce',
		'Salesforce.com':'Salesforce',
		'Salesforce Com':'Salesforce',
		'support.com':'Support.com',
		'Bank of America Corp.':'Bank of America', 
		'8X8 Inc New':'8X8 Inc',
		'Verizon Communications':'Verizon',
		'Alphabet':'Waymo',
		'Citigroup':'Citi',
		'Procter & Gamble':'Procter and Gamble',
		'Dell Technologies':'Dell',
		'UPS':'United Parcel Service',
		'Prudential Financial':'Prudential',
		'United Technologies':'United Technologies Corp. Headquarters',
		'Cisco Systems':'Cisco',
		'American Airlines Group':'American Airlines',
		'Liberty Mutual Insurance Group':'Liberty Mutual',
		'Goldman Sachs Group':'Goldman Sachs',
		'Energy Transfer Equity':'Energy Transfer Family of Partnerships',
		'United Continental':'United Airlines',
		'1-800 Flowers Com':'1-800-Flowers.com',
		'Overstock Com':'Overstock.com',
		'Stamps Com':'Stamps.com',
		'Charter Communications':'Spectrum',
		'Capital One Financial':'Capital One',
		'Twenty-First Century Fox':'Twentieth Century Fox',
		'Enterprise Products Partners':'Enterprise Products',
		'Berkley W R':'W.R. Berkley',
		'Waddell & Reed Financial':'Waddell and Reed',
		'American Financial Group':'Great American Insurance Group',
		'American Financial':'Great American Insurance Group',
		"Kohl's":'Kohls',
		'Hartford Financial Services Group':'The Hartford',
		'PG&E':'Pacific Gas and Electric Company',
		'Bank of New York Mellon':'BNY Mellon',
		'Goodyear Tire & Rubber':'Goodyear',
		"Land O'Lakes":'Land O’Lakes',
		'Guardian Life Ins. Co. of America':'Guardian Life Insurance Company',
		'Hilton Worldwide':'Hilton Corporate',
		'Reinsurance Group of America':'RGA',
		'Parker-Hannifin':'Parker Hannifin',
		'Priceline Group':'Priceline.com',
		'W.W. Grainger':'Grainger',
		'Fidelity National Information Services':'FIS Global',
		'Fidelity Natl Info':'FIS Global',
		'Public Service Enterprise Group':'PSEG',
		"O'Reilly Automotive":"O'Reilly Auto Parts",
		'Smucker J M':'J.M. Smucker',



}
